name: Build CV

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full biber

    - name: Build CV
      run: make all

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: CV
        path: src/resume.pdf
        if-no-files-found: error

    - name: Commit and push PDF
      if: github.event_name == 'push'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add output/*.pdf
        git commit -m "Update PDF" || echo "No changes to commit"
        git push