name: Build CV

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest # Use official TeX Live container
    steps:
    - uses: actions/checkout@v4
    
    - name: Build CV
      run: make all

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: CV
        path: src/resume.pdf
        if-no-files-found: error

    - name: Commit and push PDF
      if: github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global --add safe.directory /__w/Resume/Resume
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add output/*.pdf
        git commit -m "Update PDF" || echo "No changes to commit"
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git push
