name: Build CV

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full biber

    - name: Build CV
      run: make

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: CV
        path: output/latest/cv_latest.pdf

    - name: Download PDF
      uses: actions/download-artifact@v3
      with:
        name: CV
        path: downloaded-cv